apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gh-jenkins-artifactory-go-bvnvwcxt
  janus-idp.io/tekton: gh-jenkins-artifactory-go-bvnvwcxt
  backstage.io/kubernetes-id: gh-jenkins-artifactory-go-bvnvwcxt
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gh-jenkins-artifactory-go-bvnvwcxt
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
