apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gh-jenkins-artifactory-go-bvnvwcxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gh-jenkins-artifactory-go-bvnvwcxt 
  name: gh-jenkins-artifactory-go-bvnvwcxt
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gh-jenkins-artifactory-go-bvnvwcxt 
